---
- name: Create folder for ssh keys to allow access to {{ ci_hostname }}
  file: path="{{ jenkins_ssh_key_path }}" state=directory

- name: Get ssh keys to allow access to {{ ci_hostname }} from s3
  s3:
    aws_access_key: "{{ aws_key }}"
    aws_secret_key: "{{ aws_secret }}"
    region: "{{ aws_region }}"
    overwrite: True
    bucket: "{{ config_bucket }}"
    object: keys/{{ ci_hostname }}/{{ item }}
    dest: "{{ jenkins_ssh_key_path }}/{{ item }}"
    mode: get
  with_items:
    - id_rsa
    - id_rsa.pub

- name: Set permissions on private ssh key to allow access to {{ ci_hostname }}
  file: path="{{ private_jenkins_ssh_key }}" mode=0600
