---
- name: Make terraform instance dir
  file: path="{{ terraform_instance_dir }}" state=directory

- name: "Get remote terraform.tfstate from s3"
  s3:
    aws_access_key: "{{ aws_key }}"
    aws_secret_key: "{{ aws_secret }}"
    region: "{{ aws_region }}"
    overwrite: different
    bucket: "{{ config_bucket }}"
    object: "{{ config_bucket_key }}"
    dest: "{{ terraform_instance_dir }}/terraform.tfstate"
    mode: get
