---
- name: Run terraform {{ terraform_mode }}
  shell: >
    terraform {{ terraform_mode }} -no-color -input=false -var-file={{ terraform_dir }}/terraform.tfvars {{ terraform_dir }} chdir={{ terraform_dir }}
  ignore_errors: yes
  register: terraform_result

- name: Push remote state
  shell: >
    terraform remote push chdir={{ terraform_dir }}

- name: Fail on error
  fail: msg="Terraform apply failed with:\n{{ terraform_result.stderr }}"
  when: terraform_result.rc != 0
