---
- name: Run terraform destroy
  shell: >
    terraform destroy -input=false -force -refresh=false {{ terraform_dir }} chdir={{ terraform_dir }}
  ignore_errors: yes
  register: terraform_result

- name: Push remote state
  shell: >
    terraform remote push chdir={{ terraform_dir }}

- name: Fail on error
  fail: msg="Terraform destroy failed with:\n{{ terraform_result.stderr }}"
  when: terraform_result.rc != 0
