---
- name: "Push remote terraform.tfstate"
  s3:
    aws_access_key: "{{ aws_key }}"
    aws_secret_key: "{{ aws_secret }}"
    region: "{{ aws_region }}"
    overwrite: different
    bucket: "{{ config_bucket }}"
    object: "{{ config_bucket_key }}"
    src: "{{ terraform_instance_dir }}/terraform.tfstate"
    mode: put
