---
- name: Generate terraform tfvars file
  template: src=terraform.tfvars.jinja2
            dest="{{ terraform_dir }}/terraform.tfvars"
  when: terraform_mode in ['apply', 'plan']


- name: config remote state
  shell: >
    terraform remote config -backend=S3 -backend-config="bucket={{ config_bucket }}" -backend-config="key={{ config_bucket_key }}" chdir={{ terraform_dir }}

- name: pull remote state
  shell: >
    terraform remote pull chdir={{ terraform_dir }}
