---
- name: Run terraform destroy
  shell: >
    terraform destroy -input=false -force -refresh=false {{playbook_dir}}/../terraform/ chdir={{playbook_dir}}/../terraform/
  ignore_errors: yes
  register: terraform_result

- name: Push remote state
  shell: >
    terraform remote push chdir={{playbook_dir}}/../terraform/

- name: Fail on error
  fail: msg="Terraform destroy failed with:\n{{terraform_result.stderr}}"
  when: terraform_result.rc != 0