---
- name: Install libraries
  pip: name={{item}} executable={{ coreos_pypy_home }}/bin/pip
  with_items:
    - docker-py
    - boto

- name: Copy config dir over
  synchronize: >
    src={{playbook_dir}}/../config/
    dest={{ ansible_env.HOME }}/config/
    recursive=yes

- name: Kill off jenkins docker machine
  shell: docker exec {{item}} bash -c "docker-machine rm -f {{docker_machine_name}}"
  ignore_errors: yes
  with_items:
    - "{{ci_container_name}}"

- name: Kill off containers
  shell: docker rm -f {{item}}
  ignore_errors: yes
  with_items:
    - "{{backup_container_name}}"
    - "{{nginx_container_name}}"
    - "{{conf_container_name}}"
    - "{{ci_container_name}}"
    - "{{cert_container_name}}"

- name: Kill off data container
  shell: docker rm -f {{item}}
  ignore_errors: yes
  with_items:
    - "{{data_container_name}}"
  when: dump_data == 'yes'
