---
- name: Sync jenkins data volume with newly rendered config files
  docker:
    docker_api_version: "{{ docker_api_version }}"
    image: "{{data_container_tag}}"
    state: started
    pull: missing
    net: bridge
    detach: False
    command: /usr/bin/rsync -avt /rsyncdata/config/ /var/jenkins_home/
    volumes:
      - "{{data_container_path }}:/rsyncdata"
    volumes_from:
      - "{{data_container_name}}"

- name: Sync jenkins data volume with newly rendered secrets files
  docker:
    docker_api_version: "{{ docker_api_version }}"
    image: "{{data_container_tag}}"
    state: started
    pull: missing
    net: bridge
    detach: False
    command: /usr/bin/rsync -avt /rsyncdata/secrets/ /var/jenkins_home/secrets/
    volumes:
      - "{{data_container_path }}:/rsyncdata"
    volumes_from:
      - "{{data_container_name}}"

- name: Sync jenkins data volume with newly rendered job builder files
  docker:
    docker_api_version: "{{ docker_api_version }}"
    image: "{{data_container_tag}}"
    state: started
    pull: missing
    net: bridge
    detach: False
    command: /usr/bin/rsync -vrt /rsyncdata/job-builder/ /etc/jenkins_jobs
    volumes:
      - "{{data_container_path }}:/rsyncdata"
    volumes_from:
      - "{{data_container_name}}"