---
- name: Build jenkins data container
  shell: docker build -t {{ data_container_tag }} {{ data_container_path }}

- name: Run jenkins data container
  docker:
    name: "{{ data_container_name }}"
    docker_api_version: "{{ docker_api_version }}"
    image: "{{ data_container_tag }}"
    state: started
    pull: missing
    net: bridge
