---
- name: Sync data container with newly rendered files
  docker:
    docker_api_version: "{{ docker_api_version }}"
    image: "{{ data_container_tag }}"
    state: started
    pull: missing
    net: bridge
    detach: False
    command: /usr/bin/rsync {{ item.flags }} /rsyncdata/{{ item.src }}/ {{ item.dest }}
    volumes:
      - "{{ data_container_path }}:/rsyncdata"
    volumes_from:
      - "{{ data_container_name }}"
  with_items:
    - { flags: "-avt", src: "config", dest: "/var/jenkins_home/" }
    - { flags: "-avt", src: "secrets", dest: "/var/jenkins_home/secrets/" }
    - { flags: "-vrt", src: "job-builder", dest: "/etc/jenkins_jobs" }
