---
- name: Force removal of certs folder for nginx
  become: yes
  file: >
    path="{{ nginx_container_path }}/certs/"
    state=absent

- name: Create {{item}} folder for nginx
  file: >
    path="{{ nginx_container_path }}/{{item}}/"
    state=directory
  with_items:
    - certs
    - vhosts.d
    - html

- name: Official NGINX
  docker:
    name: "{{nginx_container_name}}"
    docker_api_version: "{{ docker_api_version }}"
    image: nginx
    state: started
    pull: missing
    tty: yes
    net: bridge
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d
      - "{{ nginx_container_path }}/certs:/etc/nginx/certs:ro"
      - "{{ nginx_container_path }}/vhost.d:/etc/nginx/vhost.d"
      - "{{ nginx_container_path }}/html:/usr/share/nginx/html"
