---
- name: Create folder for certs
  file: >
    path="{{ nginx_container_path }}/certs/"
    state=directory
- name: Create folder for vhosts
  file: >
    path="{{ nginx_container_path }}/vhost.d/"
    state=directory
- name: Create folder for nginx html
  file: >
    path="{{ nginx_container_path }}/html/"
    state=directory

- name: Official NGINX
  docker:
    name: "{{nginx_container_name}}"
    docker_api_version: "{{ docker_api_version }}"
    image: nginx
    state: started
    pull: missing
    tty: yes
    net: bridge
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/conf.d
      - "{{ nginx_container_path }}/certs:/etc/nginx/certs:ro"
      - "{{ nginx_container_path }}/vhost.d:/etc/nginx/vhost.d"
      - "{{ nginx_container_path }}/html:/usr/share/nginx/html"