---
- hosts: jenkins
  gather_facts: False   
  roles:    
    - { role: ssh-wait, host: "{{ ansible_ssh_host }}", delay: 5, timeout: 300 }
    - { role: ansible-coreos-bootstrap, coreos_pypy_url: 'https://bitbucket.org/squeaky/portable-pypy/downloads' }

- hosts: jenkins
  roles:
    - { role: kraken-ci }